### ISSUE TITLE
There is a space in TextAnimator implementation

### ISSUE THREAD

**Issue by nanox77** [andrewpmoore/widget_and_text_animator#5]
Hello!. Great package. I have an issue with TextAnimator and checking the library code I found this:

```dart
    for (var element in temp) {
      _words.add(element = '$element ');
    }
```

There is a space when you assign the element variable. Do you make it for a particular reason?

This is a problem if you need to center the text element. Shall we remove that space?.

Thank you!

**Comment by andrewpmoore** [comment]
Thanks for spotting that and apologies for not replying sooner, I didn't get a github notification for it.
I've just looked and it needs the space as it's trimming by space to chop up into words. I'm just about to publish a change that will trim the additional space off the last work in the list.
