### ISSUE TITLE
Change the size of the animation

### ISSUE THREAD

**Issue by giantss** [andrewpmoore/widget_and_text_animator#8]
How to change the amplitude of animation?
For example `atRestEffect: WidgetRestingEffects.bounce()`,

`bounce()`, the bounce animation amplitude is too large. I want to make its animation amplitude smaller. How should I do this?
 
![bounce](https://github.com/andrewpmoore/widget_and_text_animator/assets/13778798/8852537a-a678-4962-9d8c-61565489b05a)

**Comment by andrewpmoore** [comment]
Hi @giantss 
You can use the following `atRestEffect: WidgetRestingEffects.bounce(effectStrength:  1)`
Where `0.1` would be less of the effect and for example `2` would be a bigger effect

**Comment by giantss** [comment]
ok，Thanks.
